tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      gp sync-done aws-cli

  - name: install postgres client
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev

      # Get the IP of GITPOD and put it inside `rds/update-sg-rule` script
      gp sync-await aws-cli
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"

  - name: "Install Front-End dependencies"
    before: |
      "$THEIA_WORKSPACE_ROOT/bin/frontend/generate-env"
      cd ./frontend-react-js
      npm i
      gp sync-done "Install Front-End dependencies"

  - name: Install Back-End dependencies
    before: |
      "$THEIA_WORKSPACE_ROOT/bin/backend/generate-env"
      cd ./backend-flask
      pip install -r requirements.txt

  - name: fargate (install AWS Session Manager to access containers in fargate)
    before: |
      cd /workspace
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      session-manager-plugin

  - name: cdk
    before: |
      npm install aws-cdk -g
      cd thumbing-serverless-cdk
      npm i

  # install sharp, aws-sdk for s3-client
  - name: lambdas
    before: |
      "$THEIA_WORKSPACE_ROOT/bin/avatars/build"

  - name: "docker-compose up"
    before: |
      gp sync-await "Install Front-End dependencies"
      docker compose -f "./docker-compose-gitpod.yml" up -d --build
      gp sync-done "docker-compose up"

  - name: db&ddb-setup
    init: |
      gp sync-await "docker-compose up"
      ./bin/db/setup
      ./bin/ddb/schema-load
      ./bin/ddb/seed

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - cweijan.vscode-postgresql-client2

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
