version: "3.9"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "*"
      BACKEND_URL: "*"
    build: ./backend-flask
    ports:
      - "4567:4567"
    healthcheck: # will check URL every {interval} After {start_period} for number of {retries}
      test: wget --no-verbose --tries=1 --spider http://localhost:4567/api/activities/home || exit 1 # if wget cmd failed, will execute {exit 1}
      interval: 20s # no. seconds between executing the health check after the start_period.
      retries: 2 # no. of consecutive checks that failed to declare unhealth container.
      start_period: 20s # no. of seconds before starting health checks.
      timeout: 5s # no. of seconds to wait for a health check to complete before considering it a failure.
    volumes:
      - ./backend-flask:/backend-flask
  
  frontend-react-js:
    depends_on:
      - backend-flask
    environment:
      REACT_APP_BACKEND_URL: "http://127.0.0.1:4567"
    build:
      context: ./frontend-react-js
      dockerfile: Dockerfile.one-stage
    ports:
      - "3000:3000"
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 20s
      retries: 2
      start_period: 20s
      timeout: 10s
    # volumes:
    #   - ./frontend-react-js:/frontend-react-js

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks: 
  internal-network:
    driver: bridge
    name: cruddur